--What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender


--Which customers used a discount but still spent more than the average purchase amount?
SELECT *
FROM customer
WHERE discount_applied ='Yes'
and purchase_amount > (SELECT AVG(purchase_amount)
                        FROM customer)

						
--Which are the top 5 products with the highest average review rating?
SELECT item_purchased,AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating
limit 5

--Compare the average purchase amount between Standard and Express shipping.
SElect shipping_type,AVG(purchase_amount)
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type

--Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,COUNT(customer_id) AS total_customer,AVG(purchase_amount) AS avg_spend,SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC


--Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND (100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT
CASE
    WHEN previous_purchases = 0 THEN 'New'
    WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment,
COUNT(*) AS total_customers,
AVG(purchase_amount) AS avg_spend
FROM customer
GROUP BY customer_segment;

--What are the top 3 most purchased products within each category?


--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(*) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
--What is the revenue contribution of each age group?
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;